---
abstract: 'Create CPAN::Mini mirror with recent developer releases'
author:
  - 'David A. Golden <dagolden@cpan.org>'
build_requires:
  Test::More: 0.62
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Devel-Recent
no_index:
  directory:
    - examples
    - inc
provides:
  CPAN::Mini::Devel::Recent:
    file: lib/CPAN/Mini/Devel/Recent.pm
    version: 0.02
requires:
  CPAN: 1.92
  CPAN::HandleConfig: 0
  CPAN::Mini: 0.567
  CPAN::Mini::Devel: 0.03
  CPAN::Tarzip: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 3.27
  File::Temp: 0.2
  YAML::Syck: 1.07
  perl: 5.006
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
  repository: http://dagolden.googlecode.com/svn/
version: 0.02
